# -*- coding: utf-8 -*-
"""Untitled45.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QgvCdqEzAB9hO0HveLNCnSFTmSpUed3r
"""

import pandas as pd

df = pd.read_csv('Housing.csv')

from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential

train = df[:500]
test = df[500:]

x_train = train.drop('price', axis = 1)
y_train = train['price']
x_test = test.drop('price', axis = 1)
y_test = test['price']

train

model = Sequential()
model.add(Input((5, 1)))
model.add(Dense(4, activation = 'relu'))